### PR TITLE
Update README.md to include HACS installation steps

### PR DESCRIPTION
**Pull request by iMrLopez**
Added steps to install with HACS

### CODE REVIEW

**Comment by Aloke111** [comment]
Excellent

**Review by isbkch — APPROVED** [review]

**Comment by iMrLopez** [comment]
@chomupashchuk 
@FeikoJoosten 

can you please merge this into master? this PR helps a lot.

**Comment by FeikoJoosten** [comment]
Not sure why I’m tagged, since I don’t have write access to this repro.

**Comment by dannytsang** [comment]
@FeikoJoosten I suspect it's because you're listed as a contributor.

Changes look good to me over to @chomupashchuk

**Comment by Aloke111** [comment]
Access

**Comment by iMrLopez** [comment]
This project is sadly abandoned, closing the PR, i dont like having dangling PRs.

**Pull request closed without merging**
